"""Public catalog persistence API."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

from .database import (
    DEFAULT_DATABASE_URL,
    create_db_engine,
    create_engine_from_url,
    create_session_factory,
    create_tables,
    get_database_url,
    init_database,
    session_scope,
)
from .mapping_review import (
    MappingDecision,
    MappingOutcome,
    MappingReview,
    ReviewStatus,
    load_mapping_reviews,
    save_mapping_reviews,
    upsert_mapping_review,
)
from .orm import (
    Base,
    BenchmarkResultORM,
    BenchmarkResultRecord,
    BuildComponentORM,
    BuildComponentRecord,
    BuildShareORM,
    BuildShareRecord,
    CanonicalProductORM,
    CanonicalProductRecord,
    CompatibilityRuleORM,
    CompatibilityRuleRecord,
    GeneratedBuildORM,
    GeneratedBuildRecord,
    InteractionEventORM,
    InteractionEventRecord,
    PriceSnapshotORM,
    PriceSnapshotRecord,
    ProductEmbeddingORM,
    ProductEmbeddingRecord,
    RetailerListingORM,
    RetailerListingRecord,
    ReviewEvidenceORM,
    ReviewEvidenceRecord,
    SearchQueryORM,
    SearchQueryRecord,
    SourceProvenanceORM,
    SourceProvenanceRecord,
)
from .repository import CatalogRepository, ProductRepository
from .seed import (
    EPOCH,
    SEED_NAMESPACE,
    SeedLoadResult,
    deterministic_id,
    load_seed_data,
    load_seed_file,
    seed_catalog,
)

if TYPE_CHECKING:
    from .canonical_identity import (
        CANONICAL_IDENTITY_PREFLIGHT_SCHEMA_VERSION,
        CanonicalIdentityConflictGroup,
        CanonicalIdentityImportError,
        CanonicalIdentityMember,
        CanonicalIdentityPreflightReport,
        DuplicateProductIdGroup,
        audit_canonical_envelopes,
        audit_canonical_product_identities,
    )
    from .entity_matcher import (
        ENTITY_MATCHING_DECISION_VERSION,
        CatalogEntityMatcher,
        CatalogMatchResult,
        listing_record_from_offer,
    )
    from .er_gate import (
        ER_EVALUATION_SCHEMA_VERSION,
        ER_EVALUATION_SCHEMA_VERSION_V2,
        EntityResolutionEvaluation,
        load_entity_resolution_evaluation,
    )
    from .processed import (
        DEFAULT_MAX_JSONL_LINE_BYTES,
        REVIEW_EVIDENCE_RECORD_TYPE,
        REVIEW_EVIDENCE_SCHEMA_VERSION,
        InMemoryCatalogReader,
        ProcessedCatalogData,
        ProcessedCatalogStats,
        ReviewedMapping,
        iter_jsonl_objects,
        load_processed_catalog,
        load_review_evidence,
        load_reviewed_mappings,
        seed_processed_catalog,
    )
    from .readiness import (
        CRITICAL_COMPATIBILITY_FIELDS,
        CatalogReadinessAccumulator,
        CatalogReadinessReport,
        ProductionCatalogPolicy,
        ProductionCatalogReadinessError,
        validate_production_readiness,
    )
    from .streaming import (
        ReviewTarget,
        StreamedCatalogImportResult,
        stream_processed_catalog,
        validate_review_target,
    )


_LAZY_EXPORTS = {
    "CANONICAL_IDENTITY_PREFLIGHT_SCHEMA_VERSION": ".canonical_identity",
    "CanonicalIdentityConflictGroup": ".canonical_identity",
    "CanonicalIdentityImportError": ".canonical_identity",
    "CanonicalIdentityMember": ".canonical_identity",
    "CanonicalIdentityPreflightReport": ".canonical_identity",
    "DuplicateProductIdGroup": ".canonical_identity",
    "audit_canonical_envelopes": ".canonical_identity",
    "audit_canonical_product_identities": ".canonical_identity",
    "CatalogEntityMatcher": ".entity_matcher",
    "CatalogMatchResult": ".entity_matcher",
    "ENTITY_MATCHING_DECISION_VERSION": ".entity_matcher",
    "listing_record_from_offer": ".entity_matcher",
    "ER_EVALUATION_SCHEMA_VERSION": ".er_gate",
    "ER_EVALUATION_SCHEMA_VERSION_V2": ".er_gate",
    "EntityResolutionEvaluation": ".er_gate",
    "load_entity_resolution_evaluation": ".er_gate",
    "DEFAULT_MAX_JSONL_LINE_BYTES": ".processed",
    "InMemoryCatalogReader": ".processed",
    "ProcessedCatalogData": ".processed",
    "ProcessedCatalogStats": ".processed",
    "REVIEW_EVIDENCE_RECORD_TYPE": ".processed",
    "REVIEW_EVIDENCE_SCHEMA_VERSION": ".processed",
    "ReviewedMapping": ".processed",
    "iter_jsonl_objects": ".processed",
    "load_processed_catalog": ".processed",
    "load_review_evidence": ".processed",
    "load_reviewed_mappings": ".processed",
    "seed_processed_catalog": ".processed",
    "CRITICAL_COMPATIBILITY_FIELDS": ".readiness",
    "CatalogReadinessAccumulator": ".readiness",
    "CatalogReadinessReport": ".readiness",
    "ProductionCatalogPolicy": ".readiness",
    "ProductionCatalogReadinessError": ".readiness",
    "validate_production_readiness": ".readiness",
    "ReviewTarget": ".streaming",
    "StreamedCatalogImportResult": ".streaming",
    "stream_processed_catalog": ".streaming",
    "validate_review_target": ".streaming",
}


def __getattr__(name: str) -> Any:
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


__all__ = [
    "Base",
    "BenchmarkResultORM",
    "BenchmarkResultRecord",
    "BuildComponentORM",
    "BuildComponentRecord",
    "BuildShareORM",
    "BuildShareRecord",
    "CanonicalProductORM",
    "CanonicalProductRecord",
    "CANONICAL_IDENTITY_PREFLIGHT_SCHEMA_VERSION",
    "CanonicalIdentityConflictGroup",
    "CanonicalIdentityImportError",
    "CanonicalIdentityMember",
    "CanonicalIdentityPreflightReport",
    "CatalogRepository",
    "CatalogEntityMatcher",
    "CatalogMatchResult",
    "CatalogReadinessAccumulator",
    "CatalogReadinessReport",
    "CRITICAL_COMPATIBILITY_FIELDS",
    "CompatibilityRuleORM",
    "CompatibilityRuleRecord",
    "DEFAULT_DATABASE_URL",
    "DEFAULT_MAX_JSONL_LINE_BYTES",
    "DuplicateProductIdGroup",
    "EPOCH",
    "ER_EVALUATION_SCHEMA_VERSION",
    "ER_EVALUATION_SCHEMA_VERSION_V2",
    "ENTITY_MATCHING_DECISION_VERSION",
    "EntityResolutionEvaluation",
    "GeneratedBuildORM",
    "GeneratedBuildRecord",
    "InteractionEventORM",
    "InteractionEventRecord",
    "InMemoryCatalogReader",
    "MappingDecision",
    "MappingOutcome",
    "MappingReview",
    "PriceSnapshotORM",
    "PriceSnapshotRecord",
    "ProductEmbeddingORM",
    "ProductEmbeddingRecord",
    "ProductRepository",
    "ProcessedCatalogData",
    "ProcessedCatalogStats",
    "REVIEW_EVIDENCE_RECORD_TYPE",
    "REVIEW_EVIDENCE_SCHEMA_VERSION",
    "ProductionCatalogPolicy",
    "ProductionCatalogReadinessError",
    "RetailerListingORM",
    "RetailerListingRecord",
    "ReviewEvidenceORM",
    "ReviewEvidenceRecord",
    "ReviewedMapping",
    "ReviewStatus",
    "ReviewTarget",
    "SEED_NAMESPACE",
    "SearchQueryORM",
    "SearchQueryRecord",
    "SeedLoadResult",
    "SourceProvenanceORM",
    "SourceProvenanceRecord",
    "StreamedCatalogImportResult",
    "create_db_engine",
    "create_engine_from_url",
    "create_session_factory",
    "create_tables",
    "audit_canonical_envelopes",
    "audit_canonical_product_identities",
    "deterministic_id",
    "get_database_url",
    "init_database",
    "iter_jsonl_objects",
    "load_mapping_reviews",
    "listing_record_from_offer",
    "load_entity_resolution_evaluation",
    "load_seed_data",
    "load_seed_file",
    "load_processed_catalog",
    "load_review_evidence",
    "load_reviewed_mappings",
    "save_mapping_reviews",
    "seed_catalog",
    "session_scope",
    "seed_processed_catalog",
    "stream_processed_catalog",
    "upsert_mapping_review",
    "validate_production_readiness",
    "validate_review_target",
]
