"""High-precision retailer-listing entity resolution.

The public surface keeps candidate generation, features, models, operational decisions,
and evidence-aware evaluation usable by both offline training and the ingestion service.
"""

from .active_learning import (
    ActiveLearningBatch,
    ActiveLearningSelection,
    sample_active_learning,
)
from .blocking import CandidateBlocker, CandidatePair
from .candidate_generation import (
    BlockingScoreComponent,
    CandidateSupervision,
    DeterministicHardNegativeSampler,
    PCBlockingCandidate,
    PCDomainCandidateBlocker,
    UnlabeledHardNegativeCandidate,
    canonical_pc_category,
)
from .conflicts import NumericConflict, find_numeric_conflicts, has_numeric_conflict
from .decision import (
    MatchDecision,
    MatchOutcome,
    MatchThresholds,
    PlattCalibrator,
)
from .features import (
    FEATURE_NAMES,
    NUMERIC_CONFLICT_FEATURE_INDEX,
    PairFeatureExtractor,
    PairFeatures,
    validate_feature_matrix,
)
from .metrics import EntityResolutionEvaluation, evaluate_binary_predictions
from .models import (
    ARTIFACT_FORMAT_VERSION,
    BaseEntityResolver,
    ExactMatchBaseline,
    FeatureInput,
    LightGBMEntityResolver,
    LogisticMatchBaseline,
    load_entity_resolver,
)
from .normalization import (
    NumericFact,
    extract_numeric_facts,
    normalize_identifier,
    normalize_text,
    numeric_tokens,
    tokenize,
    unique_tokens,
)
from .records import (
    CanonicalProductRecord,
    ListingRecord,
    LabelledPair,
    pair_example_from_dict,
)
from .release_contracts import (
    ER_EVALUATION_SCHEMA_VERSION,
    ER_EVALUATION_SCHEMA_VERSION_V2,
    ER_POLICY_SCHEMA_VERSION,
    ER_RELEASE_IDENTITY_SCHEMA_VERSION,
    ER_REQUIRED_APPROVED_USES,
    ER_RIGHTS_APPROVAL_SCHEMA_VERSION,
    EntityResolutionContractError,
    EntityResolutionMatcherKwargs,
    EntityResolutionPolicy,
    EntityResolutionProductionEvaluation,
    EntityResolutionReleaseIdentity,
    EntityResolutionRightsApproval,
    ProductionCatalogPolicyKwargs,
    build_entity_resolution_release_identity,
    entity_resolution_file_sha256,
    load_entity_resolution_evaluation,
    load_entity_resolution_policy,
    load_entity_resolution_rights_approval,
    seal_entity_resolution_policy,
    seal_entity_resolution_rights_approval,
)
from .review import (
    REVIEW_QUEUE_SCHEMA_VERSION,
    HumanMatchLabel,
    ReviewConflictError,
    ReviewQueue,
    ReviewQueueItem,
    ReviewState,
    SourceUsePolicy,
)
from .serving import (
    ER_CATALOG_MATCHER_DECISION_VERSION,
    ER_HUMAN_LABEL_SOURCE,
    ER_PRODUCTION_CLAIM_SCOPE,
    ER_SERVING_EVIDENCE_FILENAME,
    ER_SERVING_EVIDENCE_SCHEMA_VERSION,
    ER_SERVING_PROJECTION_VERSION,
    EntityResolutionArtifactError,
    EntityResolutionRelease,
    EntityResolutionRuntime,
    EntityResolutionServingEvidence,
    build_entity_resolution_serving_evidence,
    entity_resolution_artifact_sha256,
    entity_resolution_model_version,
    entity_resolution_release_sha256,
    load_entity_resolution_release,
    load_entity_resolution_runtime,
)
from .synthetic import (
    SYNTHETIC_PROVENANCE,
    SyntheticEntityResolutionDataset,
    assert_all_synthetic,
    generate_synthetic_entity_resolution_data,
    synthetic_catalog,
    synthetic_pairs,
)
from .validation import (
    GroupedHumanEvaluation,
    PrecisionFirstOperatingPoint,
    calibrate_and_select_from_human_reviews,
    evaluate_grouped_human_reviews,
    evaluate_grouped_review_queue,
    select_precision_first_threshold,
    split_human_review_queue,
)
from .workflow_inputs import PCWorkflowInputs, load_controlled_pc_workflow_inputs

__all__ = [
    "ARTIFACT_FORMAT_VERSION",
    "REVIEW_QUEUE_SCHEMA_VERSION",
    "FEATURE_NAMES",
    "NUMERIC_CONFLICT_FEATURE_INDEX",
    "SYNTHETIC_PROVENANCE",
    "BaseEntityResolver",
    "ActiveLearningBatch",
    "ActiveLearningSelection",
    "BlockingScoreComponent",
    "CandidateBlocker",
    "CandidatePair",
    "CandidateSupervision",
    "CanonicalProductRecord",
    "DeterministicHardNegativeSampler",
    "EntityResolutionEvaluation",
    "EntityResolutionArtifactError",
    "EntityResolutionContractError",
    "EntityResolutionMatcherKwargs",
    "EntityResolutionPolicy",
    "EntityResolutionProductionEvaluation",
    "EntityResolutionReleaseIdentity",
    "EntityResolutionRelease",
    "EntityResolutionRightsApproval",
    "ProductionCatalogPolicyKwargs",
    "EntityResolutionRuntime",
    "EntityResolutionServingEvidence",
    "ER_HUMAN_LABEL_SOURCE",
    "ER_EVALUATION_SCHEMA_VERSION",
    "ER_EVALUATION_SCHEMA_VERSION_V2",
    "ER_POLICY_SCHEMA_VERSION",
    "ER_RELEASE_IDENTITY_SCHEMA_VERSION",
    "ER_REQUIRED_APPROVED_USES",
    "ER_RIGHTS_APPROVAL_SCHEMA_VERSION",
    "ER_CATALOG_MATCHER_DECISION_VERSION",
    "ER_PRODUCTION_CLAIM_SCOPE",
    "ER_SERVING_EVIDENCE_FILENAME",
    "ER_SERVING_EVIDENCE_SCHEMA_VERSION",
    "ER_SERVING_PROJECTION_VERSION",
    "ExactMatchBaseline",
    "FeatureInput",
    "GroupedHumanEvaluation",
    "HumanMatchLabel",
    "LightGBMEntityResolver",
    "ListingRecord",
    "LogisticMatchBaseline",
    "MatchDecision",
    "MatchOutcome",
    "MatchThresholds",
    "NumericConflict",
    "NumericFact",
    "PCBlockingCandidate",
    "PCDomainCandidateBlocker",
    "PCWorkflowInputs",
    "LabelledPair",
    "PairFeatureExtractor",
    "PairFeatures",
    "PlattCalibrator",
    "PrecisionFirstOperatingPoint",
    "ReviewConflictError",
    "ReviewQueue",
    "ReviewQueueItem",
    "ReviewState",
    "SourceUsePolicy",
    "SyntheticEntityResolutionDataset",
    "UnlabeledHardNegativeCandidate",
    "assert_all_synthetic",
    "build_entity_resolution_serving_evidence",
    "build_entity_resolution_release_identity",
    "canonical_pc_category",
    "calibrate_and_select_from_human_reviews",
    "evaluate_binary_predictions",
    "evaluate_grouped_human_reviews",
    "evaluate_grouped_review_queue",
    "extract_numeric_facts",
    "find_numeric_conflicts",
    "generate_synthetic_entity_resolution_data",
    "has_numeric_conflict",
    "entity_resolution_artifact_sha256",
    "entity_resolution_file_sha256",
    "entity_resolution_model_version",
    "entity_resolution_release_sha256",
    "load_entity_resolver",
    "load_entity_resolution_evaluation",
    "load_entity_resolution_policy",
    "load_entity_resolution_rights_approval",
    "load_entity_resolution_runtime",
    "load_entity_resolution_release",
    "load_controlled_pc_workflow_inputs",
    "normalize_identifier",
    "normalize_text",
    "numeric_tokens",
    "pair_example_from_dict",
    "sample_active_learning",
    "select_precision_first_threshold",
    "seal_entity_resolution_policy",
    "seal_entity_resolution_rights_approval",
    "split_human_review_queue",
    "synthetic_catalog",
    "synthetic_pairs",
    "tokenize",
    "unique_tokens",
    "validate_feature_matrix",
]
